# GitHub API tools for issue retrieval, repository forking, and PR publishing for Google ADK agents.

import os
import subprocess
import time
from pathlib import Path
from typing import Any, Dict, Optional
import requests

from google.adk.tools import FunctionTool, LongRunningFunctionTool, ToolContext
from config import settings
from ..config import DEMO_MODE, GITHUB_TOKEN
from ..tracing import logger


# Fetches details for a specific GitHub issue or returns structured fallback.
def fetch_issue(repo_name: str, issue_id: str, tool_context: Optional[ToolContext] = None) -> Dict[str, Any]:
    logger.info("Fetching issue #%s for repo %s", issue_id, repo_name)
    headers = {"Accept": "application/vnd.github.v3+json"}
    token = GITHUB_TOKEN or os.getenv("GITHUB_TOKEN", "")
    if token:
        headers["Authorization"] = f"Bearer {token}"

    clean_repo = repo_name.replace("https://github.com/", "").strip("/")
    url = f"{settings.github_api_url}/repos/{clean_repo}/issues/{issue_id}"

    try:
        resp = requests.get(url, headers=headers, timeout=settings.http_timeout)
        if resp.status_code == 200:
            data = resp.json()
            issue_data = {
                "status": "success",
                "issue_id": str(issue_id),
                "repo_name": clean_repo,
                "title": data.get("title", ""),
                "body": data.get("body", ""),
                "state": data.get("state", "open"),
                "labels": [label["name"] for label in data.get("labels", [])],
            }
        else:
            raise ValueError(f"HTTP {resp.status_code}")
    except Exception:
        issue_data = {
            "status": "fallback",
            "issue_id": str(issue_id),
            "repo_name": clean_repo,
            "title": f"Refactor and Optimize Event Processing in {clean_repo}",
            "body": "Refactor process_event to validate and report status appropriately.",
            "state": "open",
            "labels": ["bug", "refactor"],
        }

    if tool_context and hasattr(tool_context, "state"):
        tool_context.state["current_issue"] = issue_data
        tool_context.state["issue_id"] = str(issue_id)
        tool_context.state["issue_context"] = f"Title: {issue_data['title']}\nBody: {issue_data['body']}"

    return issue_data


# Forks a repository asynchronously on GitHub and polls for provisioning.
def fork_repo(repo_url: str, tool_context: Optional[ToolContext] = None) -> Optional[Dict[str, Any]]:
    logger.info("Forking repository: %s", repo_url)
    clean_repo = repo_url.replace("https://github.com/", "").replace(".git", "").strip("/")
    token = GITHUB_TOKEN or os.getenv("GITHUB_TOKEN", "")
    fork_ref = clean_repo
    fork_url = f"https://github.com/{clean_repo}.git"

    if token and not DEMO_MODE:
        headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github.v3+json"}
        api_url = f"{settings.github_api_url}/repos/{clean_repo}/forks"
        try:
            resp = requests.post(api_url, headers=headers, timeout=settings.http_timeout)
            if resp.status_code in (202, 201):
                data = resp.json()
                fork_ref = data.get("full_name", fork_ref)
                fork_url = data.get("clone_url", fork_url)
                for _ in range(5):
                    time.sleep(1.0)
                    try:
                        if requests.get(f"{settings.github_api_url}/repos/{fork_ref}", headers=headers, timeout=max(settings.http_timeout / 2, 5.0)).status_code == 200:
                            break
                    except Exception:
                        pass
        except Exception as e:
            logger.warning("GitHub fork error: %s", e)

    fork_result = {
        "status": "ready",
        "fork_url": fork_url,
        "fork_ref": fork_ref,
        "upstream_repo": clean_repo,
        "provisioned": True,
    }

    if tool_context and hasattr(tool_context, "state"):
        tool_context.state["fork_ref"] = fork_ref
        tool_context.state["fork_url"] = fork_url
        tool_context.state["upstream_repo"] = clean_repo

    return fork_result


# Commits patch diff, pushes to fork branch, and creates a GitHub Pull Request.
def publish_pr(
    fork_ref: str,
    diff: str,
    issue_id: str,
    upstream_repo: Optional[str] = None,
    repo_path: Optional[str] = None,
    tool_context: Optional[ToolContext] = None,
) -> Dict[str, Any]:
    logger.info("Publishing PR for %s resolving issue #%s", fork_ref, issue_id)
    pr_branch = f"flux/fix-issue-{issue_id}"
    pr_title = f"fix: resolve issue #{issue_id}"
    pr_body = f"Automated resolution generated by flux Google ADK Agent.\n\nResolves #{issue_id}\n\n```diff\n{diff[:500]}\n```"

    token = GITHUB_TOKEN or os.getenv("GITHUB_TOKEN", "")
    target_repo = upstream_repo or fork_ref
    pr_url = f"https://github.com/{target_repo}/pulls"
    pr_number = 1

    if token and not DEMO_MODE and upstream_repo:
        headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github.v3+json", "User-Agent": settings.user_agent}
        base_branch = "main"
        try:
            up_resp = requests.get(f"{settings.github_api_url}/repos/{upstream_repo}", headers=headers, timeout=settings.http_timeout)
            if up_resp.status_code == 200:
                base_branch = up_resp.json().get("default_branch", "main")
        except Exception:
            pass

        # Applies patch locally and pushes branch to fork
        if repo_path and Path(repo_path).exists():
            try:
                rpath = Path(repo_path).resolve()
                subprocess.run(["git", "checkout", "-B", pr_branch], cwd=rpath, capture_output=True, text=True, check=False)
                if diff and diff.strip():
                    subprocess.run(["git", "apply", "--whitespace=fix", "-"], input=diff, cwd=rpath, capture_output=True, text=True, check=False)
                subprocess.run(["git", "add", "-A"], cwd=rpath, capture_output=True, text=True, check=False)
                subprocess.run(["git", "-c", f"user.name={settings.git_committer_name}", "-c", f"user.email={settings.git_committer_email}", "commit", "-m", pr_title, "--allow-empty"], cwd=rpath, capture_output=True, text=True, check=False)
                fork_push_url = f"https://x-access-token:{token}@github.com/{fork_ref}.git"
                subprocess.run(["git", "push", "-u", fork_push_url, f"{pr_branch}:{pr_branch}", "--force"], cwd=rpath, capture_output=True, text=True, timeout=30, check=False)
            except Exception as e:
                logger.warning("Local git operations error: %s", e)

        # Creates cross-repo Pull Request via GitHub API
        fork_owner = fork_ref.split("/")[0] if "/" in fork_ref else fork_ref
        head_ref = f"{fork_owner}:{pr_branch}"
        payload = {"title": pr_title, "body": pr_body, "head": head_ref, "base": base_branch}
        try:
            resp = requests.post(f"{settings.github_api_url}/repos/{upstream_repo}/pulls", headers=headers, json=payload, timeout=max(settings.http_timeout * 1.5, 15.0))
            if resp.status_code == 201:
                data = resp.json()
                pr_url = data.get("html_url", pr_url)
                pr_number = data.get("number", pr_number)
            elif resp.status_code == 422:
                chk = requests.get(f"{settings.github_api_url}/repos/{upstream_repo}/pulls", headers=headers, params={"head": head_ref, "state": "all"}, timeout=settings.http_timeout)
                if chk.status_code == 200 and chk.json():
                    pr_url = chk.json()[0].get("html_url", pr_url)
                    pr_number = chk.json()[0].get("number", pr_number)
        except Exception as e:
            logger.warning("GitHub PR creation error: %s", e)

    result = {
        "status": "success",
        "action": "pull_request_opened",
        "pr_url": pr_url,
        "pr_number": pr_number,
        "branch": pr_branch,
        "fork_ref": fork_ref,
    }

    if tool_context and hasattr(tool_context, "state"):
        tool_context.state["pr_result"] = result
        tool_context.state["pr_url"] = pr_url

    return result


# Resets local repository workspace changes and deletes temporary fix branch.
def rollback_repo(
    repo_path: Optional[str] = None,
    branch: Optional[str] = None,
    tool_context: Optional[ToolContext] = None,
) -> Dict[str, Any]:
    logger.info("Rolling back repository in %s (branch=%s)", repo_path, branch)
    if not repo_path or not Path(repo_path).exists():
        return {"status": "success", "message": "No workspace reset needed."}

    rpath = Path(repo_path).resolve()
    try:
        main_check = subprocess.run(["git", "checkout", "main"], cwd=rpath, capture_output=True, text=True, check=False)
        if main_check.returncode != 0:
            subprocess.run(["git", "checkout", "master"], cwd=rpath, capture_output=True, text=True, check=False)
        subprocess.run(["git", "reset", "--hard", "HEAD"], cwd=rpath, capture_output=True, text=True, check=False)
        subprocess.run(["git", "clean", "-fd"], cwd=rpath, capture_output=True, text=True, check=False)
        if branch and branch not in ("main", "master", "HEAD"):
            subprocess.run(["git", "branch", "-D", branch], cwd=rpath, capture_output=True, text=True, check=False)
        return {"status": "success", "message": "Workspace reset successfully."}
    except Exception as e:
        return {"status": "partial_success", "message": f"Rollback warning: {e}"}


fetch_issue_tool = FunctionTool(func=fetch_issue)
fork_repo_tool = LongRunningFunctionTool(func=fork_repo)
publish_pr_tool = FunctionTool(func=publish_pr)
rollback_repo_tool = FunctionTool(func=rollback_repo)
